### ISSUE TITLE
Crash on latest a9lh

### ISSUE THREAD

**Issue by ghost** [xerpi/a9lh_linux_loader#1]
![linux error](https://cloud.githubusercontent.com/assets/18313411/21878323/408e0456-d870-11e6-9ab0-c6565b35b8d9.jpg)

**Comment by xerpi** [comment]
I've updated my a9lh installation and it works fine for me, I'm not sure where the problem is.

**Comment by Mimoja** [comment]
Can confirm the error for me. Following the 3ds.guide instructions on 11.1 i ended up with that screen
Update: Turns out that my sd card was the problem.

**Comment by Mimoja** [comment]
Turns out that my sd card was the problem.
